# Generated by Django 4.1.2 on 2022-11-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=12)),
                ('date_emp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
