# Generated by Django 4.1.2 on 2022-11-03 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_emp',
        ),
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateField(blank=True, default=datetime.date),
        ),
    ]
